---
- name: oVirt cluster upgrade
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    - passwords.yml

  vars:
    engine_fqdn: ovirt.example.com
    engine_user: admin@internal

    stop_non_migratable_vms: true

    host_statuses:
      - up

    host_names:
      - host

  roles:
    - oVirt.cluster-upgrade
